### ISSUE TITLE
Implement xconnect/l3xconnect

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk-vpp#115]
<h3> Description </h3>

Since the `wireguard` encapsulates only IP packets we need to add L3 connection support.
This can be achieved with memif mechanism (`MEMIF_MODE_API_IP`) and `l3xconnect` implementation.

**Comment by denis-tingaikin** [comment]
@edwarnicke cc

**Comment by denis-tingaikin** [comment]
@glazychev-art So I guess we need to add into memif mechanism parameter Mode and have by default L2 mode

**Comment by edwarnicke** [comment]
See also: https://jira.fd.io/browse/VPP-1975
