### ISSUE TITLE
Memif usecases failing due to 'no swIfIndex available' error in cmd-forwarder-vpp

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-vpp#162]
Can be related to  https://github.com/networkservicemesh/cmd-forwarder-vpp/commit/d25e1d01adceaf293576e92f88e4c2d9d7e9034f or https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/115
##  Logs

[Containers logs (5).zip](https://github.com/networkservicemesh/sdk-vpp/files/6305973/Containers.logs.5.zip)

## Build
https://github.com/networkservicemesh/integration-k8s-kind/pull/165/checks?check_run_id=2336135953

**Comment by edwarnicke** [comment]
Should be fixed by https://github.com/networkservicemesh/cmd-nse-icmp-responder-vpp/pull/65
