### ISSUE TITLE
move vxlan vni server/client into api repo

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-vpp#215]
The vxlan vni client and server implementation looks to be more generic for any forwarder which uses vxlan tunnel as a remote mechanism, because it basically sets tunnel srcIP, dstIP and generate/set VNI into mechanism parameter. 
This would be a reason why it can be moved under api repo (may be [here](https://github.com/networkservicemesh/api/tree/main/pkg/api/networkservice/mechanisms/vxlan)?). Please let me know your feedback.

**Comment by denis-tingaikin** [comment]
api repository should not include chain elements.
So I think probably we could add a few helepr functions for vxlan mechanism

/cc @edwarnicke

**Comment by edwarnicke** [comment]
@pperiyasamy I believe are suggesting moving this chain element:

https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/mechanisms/vxlan/vni

To a repo where it can be used without bringing in vpp dependencies.

That seems entirely reasonable to me.

I would suggest we put it in: https://github.com/networkservicemesh/sdk/tree/main/pkg/networkservice/common/mechanisms 

Thoughts?

**Comment by pperiyasamy** [comment]
@edwarnicke sure, I will move this chain element into sdk repo.

**Comment by pperiyasamy** [comment]
as the PR is merged now, closing the issue.
