### ISSUE TITLE
Wireguard: use singe port for multi-tunnel

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk-vpp#223]
### Description
Wireguard uses UDP for communication.
Currently during creation it checks to see if a udp-port is already taken and returns an error if it is. Then it stores unique port for every interface. 
### Problem
NSM needs to be able to support multiple independent Wireguard tunnels between the same pair of hosts. 
It is often attaching to the single K8s interface with AF_PACKET. It needs to block any packets not intended for it for its various tunnels.
Therefore, Wireguard for NSM needs to use a single Port for all of its Wireguard interfaces. 
### Solution
Store multiple interfaces per port:
1. Change [index_t *wg_if_index_by_port ](https://github.com/FDio/vpp/blob/baedaf374d5a060e418d1548bac4db1e0f443532/src/plugins/wireguard/wireguard_if.c#L34-L35)-> `index_t **wg_if_indexes_by_port`.
1. Check for port is in use if and only if `vec_len(wg_if_indexes_by_port[port]) == 0`. Otherwise, simply append the `wg_interface` to the list of interfaces for the port.
2. Change `wg_process_handshake` to iterate over the interfaces for the port when processing a handshake.

Estimation: 3d

**Comment by glazychev-art** [comment]
Patch for vpp:
https://gerrit.fd.io/r/c/vpp/+/32443

**Comment by denis-tingaikin** [comment]
Merged https://gerrit.fd.io/r/c/vpp/+/32443
