### ISSUE TITLE
move mechutils#ToInterfaceName into sdk or api repo

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-vpp#254]
The [mechutils#ToInterfaceName](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/tools/mechutils/mechutils.go#L101-L114) method is generic and is used  to retrieve client or endpoint container interface name from forwarder perspective, if this moved into sdk or api repo,  chain elements in other `sdk-*` can reuse it.
some of the `sdk-kernel` and `sdk-sriov `chain elements still uses `mechanism.InterfaceName(conn)`  method to retrieve interface name which is logically incorrect. for example [connectioncontextkernel ](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go#L61), because of this[ cmd-forwarder-vpp](https://github.com/networkservicemesh/sdk-vpp/pull/232#issuecomment-850071570) ci is failing when sdk-vpp adapts to use it.

**Comment by denis-tingaikin** [comment]
@edwarnicke, @pperiyasamy  We'll look at the issue. 
We'll have assigned some one from team tomorrow.

**Comment by edwarnicke** [comment]
Something to keep in mind... the solution should be:

- If the client has not assigned an interface name, assign it using the client's connection id
- If the endpoint has not assigned a name, assign it using the endpoints connection id

I suspect that putting something in api and into the client and server endpoint chains may be the correct way to handle this.

Also, please test solution with cmd-forwarder-vpp

**Comment by denis-tingaikin** [comment]
@pperiyasamy It looks like all pieces done. Closing this. Be free to reopen if we missed something.
