### ISSUE TITLE
VXLAN unexpected behaviour

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/sdk-vpp#261]
## Problem

When creating VXLAN tunnel in VPP in certan case(described below) it returns invalid `swIfindex` instead of `error`

## Detailed description

Problem arised when i've been testing 'remote forwarder death' healing scenario. 
Steps:
1. start cluster with 2 nodes 
2. start nsmgr, forwarder-vpp, nsc-vpp & nse-vpp
3. ping work as expected
4. delete pod with remote forwarder(death scenario)
5. remote nsmgr catches forwarder death, tries to restore connection, then in case of failing closes connection.
6. remote forwarder already restarted
7. local nsmgr making another request
8. local forwarder trying to create VXLAN tunnel with exactly the same parameters as before
9. response from vpp returns invalid `swIfIndex`(4294967295) instead of error and seems that tunnel was not created properly

## Possible solution
Although, it's not the root cause of the problem, i think it would be helpful to take some actions about it. 
One possible solution could be to catch this special value and handle it accordingly.

**Comment by edwarnicke** [comment]
Ah... good to know...

**Comment by edwarnicke** [comment]
> local forwarder trying to create VXLAN tunnel with exactly the same parameters as before

Any idea why that isn't prevented by this:
https://github.com/networkservicemesh/sdk-vpp/blob/0325d7c438f43c58eecd9af95e7bbc2777eab32c/pkg/networkservice/mechanisms/vxlan/common.go#L46-L48

**Comment by glazychev-art** [comment]
As I understand it, this is one of the healing cases. It was redesigned after the issue was created. I don't think this is relevant.

@denis-tingaikin @edwarnicke 
Feel free to reopen
