### ISSUE TITLE
Re-enable tapv2

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/sdk-vpp#270]
tapv2 was [disabled](https://github.com/networkservicemesh/sdk-vpp/pull/269) to work around a vpp bug.  Needs to be re-enabled once that bug is fixed.

**Comment by glazychev-art** [comment]
After reverting PR that [disabled](https://github.com/networkservicemesh/sdk-vpp/pull/269) tapv2, I found, that we have unstable `cmd-forwarder-vpp` docker tests `TestForwarderTestSuite/TestCombinations/Ethernet/*`.
Output:
```
--- FAIL: TestForwarderTestSuite (12.91s)
    --- FAIL: TestForwarderTestSuite/TestCombinations (11.73s)
        --- FAIL: TestForwarderTestSuite/TestCombinations/Ethernet (11.73s)
            --- FAIL: TestForwarderTestSuite/TestCombinations/Ethernet/Kernel (11.73s)
                --- PASS: TestForwarderTestSuite/TestCombinations/Ethernet/Kernel/Kernel (0.45s)
                --- FAIL: TestForwarderTestSuite/TestCombinations/Ethernet/Kernel/Memif (10.63s)
                --- PASS: TestForwarderTestSuite/TestCombinations/Ethernet/Kernel/Vxlan (0.65s)
    --- PASS: TestForwarderTestSuite/TestHealthCheck (0.00s)
FAIL
```
Tested with and without a new [l3xc patch](https://github.com/edwarnicke/govpp/pull/26).

**Comment by glazychev-art** [comment]
Found that the instability of these tests is not related to `tapv2`. 
Created an issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/274
