### ISSUE TITLE
Incorporating sdk-sriov functionality into sdk-vpp xconnectns chain

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/sdk-vpp#314]
sdk-sriov is very exciting.  It would be nice to be able to incorporate its functionality into cmd-vpp-forwarder.

I do understand there are some tricky bits to doing so.  Lets scope them out here so we can sort them out.

**Comment by Bolodya1997** [comment]
@edwarnicke 
I see here one little problem - currently we have some multiforwarder integration tests needed 2 different types of forwarders supporting different mechanisms. Integrating both existing forwarders to single one would make them not valid.
Would it be OK to rework these tests with custom endpoints validating the path and accepting Request only from special forwarder?

**Comment by Bolodya1997** [comment]
@edwarnicke 
Do we need here to introduce new `sriov-kernel` mechanism? I suppose that there is some difference between the kernel interface backed by NIC VF and tap kernel interface but there is totally no chance for the user to request right type of kernel interface.
On the other hand we can additionally check if Request contains SR-IOV token ID and so understand it like requesting the VF backed kernel interface and return an error if we are failing to provide it.

What do you think?

**Comment by edwarnicke** [comment]
> On the other hand we can additionally check if Request contains SR-IOV token ID and so understand it like requesting the VF backed kernel interface and return an error if we are failing to provide it.

This seems like the better choice :)

**Comment by Bolodya1997** [comment]
Currently there are the following tasks needs to be finished to complete this task:

### Merge forwarders:
1. Add generic Forwarder chain - https://github.com/networkservicemesh/sdk/pull/1045.
2. Add `labels` to support complicated `switchcase` scenarios - https://github.com/networkservicemesh/sdk/pull/1047.
3. Add SR-IOV token ID mechanism parameter on the API level - https://github.com/networkservicemesh/api/pull/110.
4. Start using SR-IOV token ID mechanism parameter from the API in `sdk-sriov` (depends on [3]) - https://github.com/networkservicemesh/sdk-sriov/pull/227.
5. Merge SR-IOV forwarder chain into the VPP forwarder chain (depends on [1, 2, 3, 4]) - https://github.com/networkservicemesh/sdk-vpp/pull/325.
6. Rework `cmd-forwarder-vpp` to use new forwarder chain - (depends on [5]) - https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/300.

### Fix tests:
1. Add reading `opa.Policies` from string to make possible forwarder selection from the Endpoint for multiforwarder test cases - https://github.com/networkservicemesh/sdk/pull/1050.
2. Configure `opa.Policies` from env to make possible ... (depends on [1]) - https://github.com/networkservicemesh/cmd-nse-icmp-responder/pull/265.
3. Rework all integration tests to the new forwarder (depends on [Merge forwarders, 2]) - https://github.com/networkservicemesh/deployments-k8s/pull/2413.

**Comment by denis-tingaikin** [comment]
@edwarnicke All PRs are merged. Can we close the issue?

**Comment by edwarnicke** [comment]
@denis-tingaikin Is it being tested in integration?

**Comment by Bolodya1997** [comment]
Done and tested.
