### ISSUE TITLE
[Calico/VPP NSM integration] `memif` and `memifproxy` files should be shared with VPP pod

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-vpp#357]
## Issue
Currently `memif` and `memifproxy` uses `/tmp/memif` and `/tmp/memifproxy` directories for storing socket files. VPP pod has no access to these files, so it work with them.
https://github.com/networkservicemesh/sdk-vpp/blob/7e89964d9e40cfc84abb6852f88540334ea0d970/pkg/networkservice/mechanisms/memif/common.go#L199-L201
https://github.com/networkservicemesh/sdk-vpp/blob/7e89964d9e40cfc84abb6852f88540334ea0d970/pkg/networkservice/mechanisms/memif/memifproxy/client.go#L82-L84

## Parent issue
https://github.com/networkservicemesh/integration-k8s-kind/issues/325

### Use shared directory
We can use `/var/run/vpp` directory instead of `/tmp` as a base for creating directories for memif socket files.

### Use `/proc/x/fd/y` path
We can replace common `/tmp/...` path with `/proc/x/fd/y` path before making VPP API request - such path is already shared, but it will additionally force us to use `hostPid: true` for the Client applications.
Currently VPP is responsible for creating memif sockets - we are only providing the path where they should be located. With this solution we need to perform additional actions for creating memif socket by ourselves before requesting VPP.

**Comment by Bolodya1997** [comment]
Possible solution with using abstract sockets - https://gerrit.fd.io/r/c/vpp/+/32271/6/src/plugins/memif/memif.api#43.

**Comment by Bolodya1997** [comment]
Should be closed with https://github.com/networkservicemesh/sdk-vpp/issues/370

**Comment by denis-tingaikin** [comment]
It seems like all PRs have merged.
