### ISSUE TITLE
[Calico/VPP NSM integration] Memif2Memif case doesn't work with Calico VPP

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-vpp#362]
## Issue
`Memif2Memif` ~with direct memif enabled~ test fails on both kind and packet clusters with Calico VPP:
1. In NSM logs there are no errors.
2. All sockets are configured in VPP.
3. VPP ping doesn't work in both sides.

**Calico currently doesn't provide any guarantees for the working `memif`, so the root cause for the issue can both be on the NSM or on the Calico side.**

## Parent issue
https://github.com/networkservicemesh/integration-k8s-kind/issues/325

## Logs
[TestMemif2Memif.zip](https://github.com/networkservicemesh/sdk-vpp/files/7098416/TestMemif2Memif.zip)

## Probable solution
~Disable direct memif for Calico VPP integration.~ Disabling direct memif doesn't work, so we need another solution.

**Comment by glazychev-art** [comment]
Memif2Memif is working with Calico VPP (included in basic suite):
https://github.com/networkservicemesh/integration-k8s-kind/blob/main/calico_test.go#L35-L37

Closing
