### ISSUE TITLE
Routes are not added to new ip-table

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk-vpp#372]
### Description
Currently we use default ip-table (`tableID==0`). 
But if we add a new one and trying to add a new route via API (`IPRouteAddDel`) - it is not added.
If we do the same via `vppctl` - it is added correctly.

Need to find a solution for the API.

**Comment by edwarnicke** [comment]
@glazychev-art Are you trying to add the route to a differerent tableID?  Are you setting the [TableID](https://github.com/edwarnicke/govpp/blob/1534cf6ada425a1f41fb6ae6da89ae793ae1f6cf/binapi/ip/ip.ba.go#L152) in the IPRouteAddDel.IPRoute?

**Comment by glazychev-art** [comment]
@edwarnicke
You are absolutely right. I set the `TableID` in the wrong place - in the `Path`.
It seems to work now.
Thank you!

**Comment by edwarnicke** [comment]
@glazychev-art Setting the TableID in the Path does a *different* interesting thing... it allows cross fib table routing (which I don't think we need to do... but is its own interesting beast :) ).
