### ISSUE TITLE
`govpp` is leaking channels on each `core.(*Connection).Invoke()`

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-vpp#391]
## Current behavior
`govpp` is leaking channels on each `core.(*Connection).Invoke()`:
![image](https://user-images.githubusercontent.com/20160689/134666931-aefeb49d-d05f-4259-b46d-7f5096928cf8.png)
[nse-firewall-vpp-5c7588d55f-9zwxz.pb.gz](https://github.com/networkservicemesh/sdk-vpp/files/7225284/nse-firewall-vpp-5c7588d55f-9zwxz.pb.gz)

## Issue
https://lists.fd.io/g/govpp-dev/topic/govpp_is_leaking_channels_on/85836420
`core.(*Connection).Invoke()` creates a new stream and doesn't close it:
https://github.com/FDio/govpp/blob/a5739cb7160349f96c428995049ff61411689ea0/core/stream.go#L68-L85

## Possible solution on our side
We can create some wrapper implementing `api.Connection` interface:
```go
type SafeConnection struct {
	api.Connection
}

func (c *SafeConnection) Invoke(ctx context.Context, req api.Message, reply api.Message) error {
	stream, err := c.NewStream(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = stream.Close() }()

	if err := stream.SendMsg(req); err != nil {
		return err
	}

	rep, err := stream.RecvMsg()
	if err != nil {
		return err
	}
	reflect.ValueOf(reply).Elem().Set(reflect.ValueOf(rep).Elem())

	return nil
}
```

**Comment by Bolodya1997** [comment]
@edwarnicke @denis-tingaikin 
cc

**Comment by edwarnicke** [comment]
@Bolodya1997 Could you file a JIRA jira.fd.io ? Again the GoVPP project?

**Comment by edwarnicke** [comment]
(or even push a gerrit to fix it: gerrit.fd.io )

**Comment by Bolodya1997** [comment]
> (or even push a gerrit to fix it: gerrit.fd.io )

Pushed to gerrit - https://gerrit.fd.io/r/c/govpp/+/33824/1.

**Comment by Bolodya1997** [comment]
@edwarnicke 
Patch was merged, can you please update [your `govpp` repo](https://github.com/edwarnicke/govpp)?
