### ISSUE TITLE
Fix SwInterfaceDump filtering for interface name in case of remote vlan mechanism

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/sdk-vpp#494]
When more sub-interface should be created on the same interface with different VLAN ID, the list of host interfaces contains the already created interfaces. This lead to a fault in cmd-forwarder-vpp and can not set the sub-interface. For e.g. the dump for eth1 contains host-eth1, host-eth1.100, host-eth11 ...

**Comment by denis-tingaikin** [comment]
@edwarnicke Is this issue release blocker?

**Comment by edwarnicke** [comment]
@ljkiraly Merged #495

**Comment by ljkiraly** [comment]
Thanks @edwarnicke
