### ISSUE TITLE
Cleanup interfaces before the forwarder termination

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk-vpp#516]
## Description

**_This problem is relevant if we use shared VPP (Calico)_**
 
 We know that when users update the forwarder, the pod restarts without saving the name. In this case, the correct solution is to remove the interfaces before terminating.

We have 2 options for this case:

### 1. Add `cleanup` chain element that works with metadata ### 
It will store the delete functions in the metadata. As soon as the chain `context.Done`, these functions will be called.
We also need to wait for all interfaces to be removed before terminating the application. To do this, we can use a channel in this chain element and wait for event here - https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/main/main.go#L282

**_Disadvantages:_** 
**A.** We need to add the delete function into each element of interest to us (for example, into mechanisms, cross-connects ...). It looks like:
```
func createTapInterface(...) {
....
cleanup.Store(ctx, isClient, "tap", func() error {
	_, err := tapv2.NewServiceClient(vppConn).TapDeleteV2(context.Background(), &tapv2.TapDeleteV2{
		SwIfIndex: rsp.SwIfIndex,
	})
	return err
})
...
}
```
**B.** Removing elements will be random. This affects us because for example the L3XC must be removed before the interfaces. I created a bug in JIRA - https://jira.fd.io/browse/VPP-2019

### 2. Monitor own connections and `Close()` before termination ### 
We can do `MonitorConnections()` before termination and call `Close()` on the `endpoint` in the `main` func - 
https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/main/main.go#L195

To prevent calling a Request on other elements (manager, another forwarder) - we can add a chainCtx check in the `connect.Client` https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/connect/client.go

_**Possible problem**_: 
Since the chain context is already Done at the time of the `MonitorConnections()` and `Close` call - there may be problems

### 3. Add `cleanup` chain element that calls `Close()` ###
This chain element will call `Close()` as soon as the `chainCtx.Done`, using `eventFactory := begin.FromContext(ctx)`.

To prevent calling a Request on other elements (manager, another forwarder) - we can add a chainCtx check in the `connect.Client` https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/connect/client.go

We also need to wait for all interfaces to be removed before terminating the application. To do this, we can use a channel in this chain element and wait for event here - https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/main/main.go#L282

_**Possible problem**_: 
Since the chain context is already Done at the time of the `Close` call - there may be problems

**Comment by edwarnicke** [comment]
Option 3 " Add cleanup chain element that calls Close()" looks good.  We may have a small number of places we need to clean up wrt the chainCtx being closed when we call Close... but overall its a nice simple approach.

**Comment by denis-tingaikin** [comment]
@edwarnicke Should this chain element close remote side? In my mind for Calico  cases - no, for SDK usage - yes.

**Comment by edwarnicke** [comment]
@denis-tingaikin Could you say more about what you man by 'close the remote side' ?

**Comment by denis-tingaikin** [comment]
@edwarnicke means do not close other datapath parts.  Because the forwarder can return back and heal connection. Otherwise other datapath parts could be closed by `timeout`.

**Comment by edwarnicke** [comment]
@denis-tingaikin How would we accomplish that here?

**Comment by denis-tingaikin** [comment]
@edwarnicke

I think we can do something like this.

```go

type cleanupClient struct{
     chainCtx context.Context
     cleanup bool //TODO fix data races
}

func NewClient(chainCtx context.Context) networkservice.NetworkServiceClient {
	return &cleanupClient{
		chainCtx context.Context,
	}
}

func (c *cleanupClient) Request(ctx context.Context, request *networkservice.NetworkServiceRequest, opts ...grpc.CallOption) (*networkservice.Connection, error) {
	resp, err := next.Client(ctx).Request(ctx, request, opts)
	if err == nil {
	     factory := begin.FromContext(ctx)
              go func() {
		              <-c.chainContext.Done()
		              c.cleanup = true
		              factory.Close()
              }()	
	}
	return resp, err
}

func (c *cleanupClient) Close(ctx context.Context, conn *networkservice.Connection, opts ...grpc.CallOption) (*empty.Empty, error) {
	if c.cleanup {
		if cc, ok := clientconn.Load(ctx); ok {
			cc.Close()
			clientconn.Delete(ctx) 
		}
	}
	return next.Client(ctx).Close(ctx, conn, opts)
}
```

Additional functionally is located before `connect` client in the client chain https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/client/client.go#L68

So then we can just close our `cc` related to remote side.

**Comment by edwarnicke** [comment]
This is good for the forwarder case... but what about the originating NSC case?

If I have:

NSC -> ... -> NSE

and the NSC itself is being terminated, we probably want to close out the connection including the remote pieces.

My guess is we could handle this easily with a With Option (and we would also need a With Option for the channel @glazychev-art mentioned for letting the main block till the Close is finished.

**Comment by denis-tingaikin** [comment]
Sounds good.

**Comment by denis-tingaikin** [comment]
Finally our solution is:

1. Implement cleanup client chain element https://github.com/networkservicemesh/sdk-vpp/issues/516#issuecomment-1066154322 @glazychev-art Note: begin factory is passing from begin.Server chain element. So when we'll call close from the client we'll close servers and clients.
2. Add an option for closing `cc` from clientconn and use it for forwarders.
3. Add an option for waiting cleanup done and use it for forwarders.

**Comment by glazychev-art** [comment]
Closed with https://github.com/networkservicemesh/sdk/pull/1246
