### ISSUE TITLE
Add health checks for vpp based apps

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-vpp#737]
## Motivation

We'd added datapath checks for kernel ifaces. https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/tools/heal/liveness_check.go#L58

We also need to add datapath checks for memif and vpp bases interfaces.

**Comment by denis-tingaikin** [comment]
@edwarnicke We're planning to add ping api for vpp  (based on this question https://lists.fd.io/g/vpp-dev/topic/questions_about_ping_and/100794944?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,100794944,previd%3D1692295131601774842,nextid%3D1690889671058029363&previd=1692295131601774842&nextid=1690889671058029363). We could use ping api for datapath checking for our vpp apps.

Don't you mind?

**Comment by edwarnicke** [comment]
@denis-tingaikin Please do

**Comment by denis-tingaikin** [comment]
Done!
